### ISSUE TITLE
When evaluating slicing, validator does not recognize subelement as fixed via pattern on parent

### ISSUE THREAD

**Issue by wardweistra** [FirelyTeam/firely-validator-api#336] opened 2024-07-16 11:36 UTC
**Describe the bug**
See https://chat.fhir.org/#narrow/stream/291844-FHIR-Validator/topic/Da.20Vinci.20CRD.20Profile.20Patient.20and.20PatientDeident.20failling/near/451738203

* Slicing is (also) set on `identifier:type.coding.system`.
* `type.coding.system` is fixed in the slice via a pattern on `type`
* Validator complains:
```
Failed to convert ElementDefinition at Patient.identifier:MRIdentifier in profile http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient: The value discriminator should have a 'fixed[x]', 'pattern[x]' or binding element set on 'Coding.system'.
```

**To Reproduce**
1. Validate the below example against `hl7.fhir.us.davinci-crd 2.0.1 ` package, eg with https://simplifier.net/validator

**Expected behavior**
No error

Example:

```json
{
    "resourceType": "Patient",

"meta": {

"lastUpdated": "2024-07-15T00:00:00-07:00",
"profile": "http://hl7.org/fhir/us/davinci-crd/StructureDefinition/profile-patient",

},

"extension": [{

"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-race",

"extension": [{

"url": "ombCategory",

"valueCoding": {

"system": "urn:oid:2.16.840.1.113883.6.238",

"code": "2106-3",

"display": "White"

}

}, {

"url": "text",

"valueString": "White"

}

]

}, {

"url": "http://hl7.org/fhir/us/core/StructureDefinition/us-core-ethnicity",

"extension": [{

"url": "ombCategory",

"valueCoding": {

"system": "urn:oid:2.16.840.1.113883.6.238",

"code": "2135-2",

"display": "Hispanic or Latino"

}

}, {

"url": "text",

"valueString": "Hispanic or Latino"

}

]

}

],

"identifier": [{

"type": {

"coding": [{

"system": "http://hl7.org/fhir/us/carin-bb/CodeSystem/C4BBIdentifierType",

"code": "um",

"display": "Unique Member ID"

}

]

},

"system": "someOrg.org/med/member-id",

"value": "100"

}, {

"type": {

"coding": [{

"system": "http://terminology.hl7.org/CodeSystem/v2-0203",

"code": "MB",

"display": "Member Number"

}, {

"system": "http://terminology.hl7.org/CodeSystem/v2-0203",

"code": "MR",

"display": "Medical record number"

}

]

},

"system": "someOrg.org/med/member-number",

"value": "60000000000100"

}

],

"active": true,

"name": [{

"family": "Oelkers",

"given": ["Cullin", "Oelkers"],

"prefix": ["Mr."]

}

],

"telecom": [{

"system": "phone",

"value": "1669957156",

"use": "home"

}, {

"system": "phone",

"value": "1688696772",

"use": "home"

}, {

"system": "phone",

"value": "1318468804",

"use": "home"

}, {

"system": "email",

"value": "Cullin.Oelkers999@gxmail.com"

}

],

"gender": "male",

"birthDate": "1933-11-03",

"address": [{

"use": "home",

"type": "both",

"line": ["4538 ARROWROOT"],

"city": "SALTON CITY",

"state": "CA",

"postalCode": "92274",

"period": {

"start": "0001-01-01",

"end": "9999-12-31"

}

}, {

"use": "home",

"type": "both",

"line": ["360 EAST F ST"],

"city": "REDLANDS",

"state": "CA",

"postalCode": "92375",

"period": {

"start": "2020-01-01",

"end": "9999-12-31"

}

}

],

"communication": [{

"language": {

"coding": [{

"system": "urn:ietf:bcp:47",

"code": "en",

"display": "English"

}, {

"system": "urn:ietf:bcp:47",

"code": "es",

"display": "Spanish; Castilian"

}

]

}

}

]

}

```

**Comment by wardweistra** [comment] 2024-07-17 12:42
As commented on Zulip, I think this slicing on two elements is probably a mistake. But the fact that the (old?) validator doesn't seem to recognize that the subelement is fixed when a pattern is set on the parent could be indicative of a real issue.

First steps for someone picking this up:
* Reproduce with new validator
* Reproduce with only slice on `type.coding.system` and fix `system` indirectly via a pattern on `type` (or `coding`)

**Comment by wardweistra** [comment] 2024-07-18 12:09
Implementer [reported](https://chat.fhir.org/#narrow/stream/291844-FHIR-Validator/topic/Da.20Vinci.20CRD.20Profile.20Patient.20and.20PatientDeident.20failling/near/452140769) to be encountering this while using firely.fhir.validation.r4 (2.3.0)

**Comment by mmsmits** [comment] 2024-09-05 08:16
We should look at the SchemaBuilders here. The discriminator processor complains that it can't find `fixed[x]` or `pattern[x]`.

This could result in a couple of outcomes:
- The profile is wrong
- The profile is wrong, but the error can be improved
- The validator is wrong and should be fixed.

**Comment by ewoutkramer** [comment] 2024-09-17 12:01
I did analysis on this issue, and -as we expected- the problem lies in the fact that the `value` discriminator path points to `type.coding.system`, and the ElementDefinition at that position has no fixed[x], pattern[x] or value[x]. 

There is another discriminator (that has a different path), that has a pattern [x] that has a value that includes a value for the coding.system, but that's a value in a _Coding instance_, it's not a value/fixed/pattern on the path given in the value discriminator. 

To put it otherwise: the path in the discriminator must point to an _ElementDefinition_ with the needed information, not to an instance location of a FHIR instance value included somewhere in another discriminator's ElementDefinition's fixed[x]. 

To quote the spec:

> Each slice must use the [element definition](http://hl7.org/fhir/R5/elementdefinition.html) for the element(s) in the discriminator(s) to ensure that the slices are clearly differentiated (...) 

> If the type is value, or pattern, then the element definition must use either: ElementDefinition.fixed[x] or ElementDefinition.pattern[x]  or
if the element has a terminology binding, a required binding (...)

The element for the discriminator "type.coding.system" does not use fixed[x], pattern[x] or a binding, so we return an error.

It would be rather hard to do otherwise, since other discriminators may have fixed[x] instances, or patterns with multiple instance values that may overlap, navigate deep into the instance, all separate from the path specified in the discriminator.

The reproduction of this issue can be found in branche 336-discriminator-without-value, if we want to continue exploring this issue.

**Closed as completed by ewoutkramer** 2024-09-17 12:01 UTC
