### ISSUE TITLE
Unexplainable error in current and new validator on Observation.valueQuantity[0]

### ISSUE THREAD

**Issue by MatthijsvdWielen** [FirelyTeam/firely-validator-api#314] opened 2024-05-08 08:05 UTC
I made a simple reproduction of an error reported by a user. The error occurs when adding the extensions to the elements. 

1 [extension is made for Observation.value[x]](https://simplifier.net/AReproductionPNT/ObservationUnit/~xml)
1[ extension is made for Quantity](https://simplifier.net/AReproductionPNT/MyExtension/~xml)

This leads to the following 2 profiles:
[Profile with extension on Observation.value[x]](https://simplifier.net/areproductionpnt/errorobservation)

[[Profile with extension on slices on Observation.value[x] ](https://simplifier.net/areproductionpnt/noerrorobservation)

2 identical examples result in an error for the example on the profile with the extension on Observation.value[x]

[Example with error](https://simplifier.net/areproductionpnt/hc40-orderentry.observation/$validate)

[Example without error](https://simplifier.net/areproductionpnt/hc40-orderentry.observation-duplicate-2/$validate)

Other than the Extension StructureDefinition.context, both extensions only have the following constraint. 
![image](https://github.com/FirelyTeam/firely-validator-api/assets/60686559/7ab15120-3618-4e74-b808-67022b544476)

**Comment by mmsmits** [comment] 2024-09-12 12:42
Duplicate of #298

**Closed as completed** 2024-09-16 11:24 UTC
Labels: needs research
